# Generated by Django 5.2.17 on 2026-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncedrecord',
            name='unique_synced_entity_record',
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['user', 'revoked_at', 'expires_at'], name='tracking_ac_user_id_6b9d00_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'status'], name='tracking_br_company_279420_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'name'], name='tracking_co_status_547ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'branch', 'updated_at'], name='tracking_cu_company_6924f7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone'], name='tracking_cu_company_e447fa_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'last_seen_at'], name='tracking_de_company_9ef283_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch', 'last_seen_at'], name='tracking_de_branch__a736da_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'branch', 'updated_at'], name='tracking_in_company_a2280a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'barcode'], name='tracking_in_company_f74f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'branch', 'updated_at'], name='tracking_su_company_38eb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'phone'], name='tracking_su_company_43bde0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'branch', 'kind', 'transaction_date'], name='tracking_tr_company_f23270_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'status', 'transaction_date'], name='tracking_tr_company_0547bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncedrecord',
            constraint=models.UniqueConstraint(fields=('entity', 'record_id', 'company'), name='unique_synced_entity_record_company'),
        ),
    ]
